spring:
  flyway:
    enabled: false
  dataSource:
    url: jdbc:mysql://127.0.0.1:3306/user_database?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

# Project properties
petstore:
  app:
    auth:
      host: http://localhost:8082
      authorize: /ath/authorize
      role: /ath/role
    env: dev
    module: user-core