spring:
  flyway:
    enabled: true
    baselineOnMigrate: true
    schemas: user_database
    name: user_database
    defaultSchema: user_database
## For local
#    dataSource:
#      url: jdbc:mysql://127.0.0.1:3306/user_database?createDatabaseIfNotExist=true
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#  dataSource:
#    url: jdbc:mysql://127.0.0.1:3306/user_database?createDatabaseIfNotExist=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082

# Project properties
petstore:
  app:
    env: dev
    module: user
