openapi: 3.0.0
info:
  title: Pet Store Pet Service
  version: 1.0.0
  description: This service handles pet entities within the Pet Store system.
servers:
  - url: http://petstore.samplehost.com/
    description: Sample
paths:
  /pet:
    post:
      summary: Add a new pet to the store
      operationId: addPet
      tags:
        - pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Pet added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '405':
          description: Invalid input

    put:
      summary: Update an existing pet
      operationId: updatePet
      tags:
        - pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Pet updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
        '405':
          description: Validation exception

  /pet/findByStatus:
    get:
      summary: Finds Pets by status
      operationId: findPetsByStatus
      tags:
        - pet
      parameters:
        - name: status
          in: query
          required: true
          schema:
            type: string
            enum: [available, pending, sold]
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'

  /pet/{petId}:
    get:
      summary: Find pet by ID
      operationId: getPetById
      tags:
        - pet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found

    delete:
      summary: Deletes a pet
      operationId: deletePet
      tags:
        - pet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Pet deleted successfully
        '404':
          description: Pet not found

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - photoUrls
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        photoUrls:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: Pet status in the store
          enum: [available, pending, sold]

    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string