CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    first_name VARCHAR(60) NOT NULL,
    last_name VARCHAR(60) DEFAULT NULL,
    email VARCHAR(150) NOT NULL,
    address TEXT DEFAULT NULL,
    birthday DATE DEFAULT NULL,
    phone VARCHAR(60) DEFAULT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_by VARCHAR(30) DEFAULT NULL,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_by VARCHAR(30) DEFAULT NULL
);