CREATE TABLE IF NOT EXISTS pet (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    category_id VARCHAR(50) NOT NULL,
    store_id VARCHAR(50) NOT NULL,
    status VARCHAR(1) NOT NULL,
    birthday DATE DEFAULT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_by VARCHAR(30) DEFAULT NULL,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_by VARCHAR(30) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS category (
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT DEFAULT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_by VARCHAR(30) DEFAULT NULL,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_by VARCHAR(30) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS pet_image (
    pet_id VARCHAR(50) NOT NULL PRIMARY KEY,
    image_url TEXT NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_by VARCHAR(30) DEFAULT NULL,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_by VARCHAR(30) DEFAULT NULL
);